### ISSUE TITLE
Detach the http://spectrefleet.com/news/ page from Wordpress

### ISSUE THREAD

**Issue by Argure** [Spectre-Gaming/Spectre-Fleet-Website#1]
Detach the http://spectrefleet.com/news/ page from Wordpress, and create a news page that auto-populates from mails sent the the Spectre Fleet mailing list. Look into ways that people can interact with this page, such as RSS, etc.

**Comment by Argure** [comment]
I think this is best done using the EVE API, either XML or CREST. I'm unsure if this would actually require an active subscription. You can manipulate the EVE API access even without an active sub, but I am not sure whether emails from the mailing list are properly delivered when the account is unsubbed. Alternatively, one of the Spectre Fleet commanders could need to generate an API for e-mail, but this would give access to /all/ of their e-mail so a far from ideal solution.

A second thing to keep in mind is to make sure only e-mails from Spectre Fleet commanders, FC's etc. will actually show up on the website. Should be easily done by checking against a whitelist, e.g. an ACL we might already have to implement anyway. Example pseudocode:

```
public void checkEmailSender(String SenderName) {
    boolean isAllowed = ACLClass.CheckIfExists(SenderName);
    if isAllowed(true) {
        postEmail();
    }
}
```

**Comment by JamesMartinSaama** [comment]
I think the requirements here are:

1) Need to use the API to get only Eve ingame emails
2) Need to get each of the spectrefleet mailers separately
3) Filter to only approved spectrefleet commanders (how do we tell who is a commander / active commander / legacy commander / FC ?)
4) Display the header, body and sender of the email

I think calling the API is only about half the battle. we may need some way to store commander configs. We could make a config file and just edit it or we could actually put a database there. I think some sort of config would be fastest path to success but a database will probably be a long term solution but at the cost of significant complexity.

**Comment by JayneF** [comment]
We can always start with displaying all mails sent the "Spectre Fleet" mailing list, since that list is tightly controlled by myself. Most emails, when not from a commanders, are forwarded/approved by a commander anyway. Also, API:

ID: 2998486
Verification Code: wL7VpSdTsoq9pzvMK1NgViSOwTTUkoVjSDG5pcMZK3ZhRddulqsAcgzBw0jfzD16

**Comment by Argure** [comment]
@JayneF can you verify that API key still exists and is valid? I currently receive an authentication failure.

**Comment by JayneF** [comment]
Key ID: 4640084
Verification Code: jjzEBe5ZPAqN5JgD0LpN1t5F9TKDU51Y3quaLPZTNLfHyIBgopdCbGd5ks6Xz8Zy
Access Mask: 536874496

New API key specifically for mails, mailing lists, chat channels, etc.

**Comment by JayneF** [comment]
News page has been detached from wordpress, need to prioritize having a new news page that pulls from the Spectre Fleet mailing list. Bounty increased to 1b ISK

**Comment by JayneF** [comment]
also - is it possible to selectively tweet out mails to the mailing list?

for example [FLEET] in the subject line would push the subject line to the SF twitter account?

**Comment by Msoenn** [comment]
https://dev.twitter.com/rest/reference/post/statuses/update
Probably can do that.
I'm calling dibs on this project. I'm going to set up a MySQL database to log all mail messages from the Spectre Fleet mailing list and then have a cron job running a python script that will pull them all on an interval and insert them into the MySQL database. The news page will then simply query this list and display most recent (10?) messages from the mailing list.

**Comment by unkwntech** [comment]
Before we do this lets get a little more coordinated, We deff need MySQL and a cron job is the best way to go about it, but python....?  And lets the the database in order first with the rest of our wishlist.

**Comment by Msoenn** [comment]
Ok I lied it's going to be CLI PHP

**Comment by unkwntech** [comment]
This task is was completed and any future changes merit a new issue.
