### ISSUE TITLE
twitch integration

### ISSUE THREAD

**Issue by JayneF** [Spectre-Gaming/Spectre-Fleet-Website#10]
We're going to start streaming out of http://www.twitch.tv/spectrefleet

I'd like a page on the website dedicated to this. At the very least, have the broadcast embeded, although I think twitch has an API which we many find some use in.

**Comment by Msoenn** [comment]
<a class="embedly-card" href="http://twitch.tv/spectrefleet">SpectreFleet</a>
<script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>

**Comment by Msoenn** [comment]
`<a class="embedly-card" href="http://twitch.tv/spectrefleet">SpectreFleet</a>
<script async src="//cdn.embedly.com/widgets/platform.js" charset="UTF-8"></script>`

**Comment by 5car1z** [comment]
The local twitch embed code in case we need it again. `<a class="embedly-card" href="http://www.twitch.tv/spectrefleet">SpectreFleet</a>
<script src="/js/twitch.min.js" type="text/javascript"></script>`

**Comment by JayneF** [comment]
using youtube gaming instead, page implemeted, bounty paid to will/ibn
