### ISSUE TITLE
Reimplement style.css

### ISSUE THREAD

**Issue by Argure** [Spectre-Gaming/Spectre-Fleet-Website#12]
The current main stylesheet is a bit of a mess. Not just in standards, but it also has a lot of unused declarations and has entire libraries just pasted in.

**Comment by Argure** [comment]
I think the best way to go about this is to simply start a new stylesheet. The entire thing can be branched off and then reimplemented. Giving that most of the current functionality is bootstrap it can drastically reduce the size and complexity of style.css.

The downside is that it's still a big undertaking and would require working off a separate branch just for this; and will likely lead to merge conflicts as development on master progresses.

**Comment by JayneF** [comment]
This needs to be prioritized. We'll talk about this on Saturday at 2200 UTC.

**Comment by unkwntech** [comment]
If anything needs a bounty it's this.  God knows it's a big deal.

**Comment by unkwntech** [comment]
This task is going to be rolled into a new one, I'm closing this.
