### ISSUE TITLE
Implement a shared live development page at http://dev.spectrefleet.com/ 

### ISSUE THREAD

**Issue by Argure** [Spectre-Gaming/Spectre-Fleet-Website#2]
I have no fucking idea what this means, but it's apparently to "set up a git repository on the live machine, and every time a git event happens, it triggers the CI to do something."

**Comment by Argure** [comment]
This is something that likely can only be done by Will as installing a CI that also performs system level operations would require root access.

**Comment by JayneF** [comment]
Here's an idea:

have an additional page, update.spectrefleet.com which has essentially two buttons, one to update dev.spectrefleet.com page, and another to update the www.spectrefleet.com page, the latter of which would require a password. Thoughts @Msoenn ?

**Comment by Msoenn** [comment]
https://github.com/Spectre-Gaming/Spectre-Fleet-Website/settings/hooks

**Comment by Msoenn** [comment]
`if ( $_POST['payload'] ) {
  shell_exec( 'cd /srv/www/git-repo/ && git reset --hard HEAD && git pull' );
}`

**Comment by Msoenn** [comment]
This is done.
