### ISSUE TITLE
Look into integrations for Slack, if necessary.

### ISSUE THREAD

**Issue by Argure** [Spectre-Gaming/Spectre-Fleet-Website#6]

**Comment by Argure** [comment]
Slack integration could be highly useful for development by passing notifications to Slack through the IRC gateway. GitHub has an IRC hook by default but it's terrible. http://n.tkte.ch/ is a much more powerful alternative.

**Comment by 5car1z** [comment]
Mentioned this in Slack: Could be done with [Notifico](http://n.tkte.ch/) and https://github.com/ekmartin/slack-irc but seems a bit extreme for what it's worth so the default Github Slack integration has been enabled! \o/

**Comment by JayneF** [comment]
Confirmed Complete
