### ISSUE TITLE
Bug hunting

### ISSUE THREAD

**Issue by Argure** [Spectre-Gaming/Spectre-Fleet-Website#7]
The website was a designed by a single guy and there is likely spaghetti code, get yourself familiar with the code and see if there are any major problems we need to address with the foundation code before we start building.

**Comment by JayneF** [comment]
Need a few people doing this.

**Comment by JamesMartinSaama** [comment]
I will take up this task for bug testing in terms of functional testing what is on dev. I will probably write test cases this weekend and put them into the wiki. 

We still need someone to put up their hand for a code review.

**Comment by unkwntech** [comment]
This task is no longer required as we resolve this with new code and rewrites of the front end. Closed.
