### ISSUE TITLE
update and simplify the commanders page at http://www.spectrefleet.com/commanders 

### ISSUE THREAD

**Issue by JayneF** [Spectre-Gaming/Spectre-Fleet-Website#8]
Remove all FCs and JFCs until we have a way of keeping track of them as an organization, only include commanders. Jayne Fillon, Douglas Aurelius, Nilez duLoup, Apex Aubaris, Vorn, and RiotRick. Also make the formatting for this page less aids, so that it doesn't have to be typed in invidiually anytime anything changes - open for suggestions on how to do this.

**Comment by Msoenn** [comment]
Gonna migrate that list into a database, then we'll have to make some sort of basic authed CMS on the web page where we can edit this so there's no need to manipulate the database directly.

**Comment by JayneF** [comment]
Doug keeps a gdoc containing out most up to date FC list, so talk to him to get the information. The information of the website is extremely outdated if not completely wrong.
